name: Gaskeun
on: [push, pull_request]
jobs:
  build:
    name: Setup
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1, 2, 3, 4]
        flag: [A, B, C, D, E]
    timeout-minutes: 60
    env:
        NUM_JOBS: 60
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: build
      run: |
        echo a
